### ISSUE TITLE
Measure user activity in sandbox systems

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-resources#22]
In the newly generated sandbox systems we should measure which features are used by users. Drop in a hotjar/gtm script. We should also notify the users that we'll be collecting anonymous usage data so we can improve our demo systems' functionality.

**Comment by herflis** [comment]
@borsi What do you mean with "We should also notify the users that we'll be collecting anonymous usage data"?

**Comment by borsi** [comment]
@herflis We have to add the cookie popup and extend the privacy policy page. Once you added the "code" for the popup, please assign me to the issue and I'll make the changes to the P&P.

**Comment by borsi** [comment]
+ don't forget to check if the P&P link is an absolute or relative url.
