### ISSUE TITLE
Jobs site - resource modifications

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-resources#23]
### Change the following Hungarian resources to English on the applicetion form:
- KAPCSOLAT -> Contact
- Név * -> Name
- E-mail *
- LinkedIn
- Telefon * - Phone
- Mikor hívhatunk? - When can we call you?
- MOTIVÁCIÓ - Motivation
- ÖNÉLETRAJZ - CV document
- Ide kattintva kiválaszthatod az önéletrajzod - You can select your CV by clicking here
- A mérete nem lehet nagyobb mint 5 MB - File size should not exceed 5MB
- Choose File

### Remove these checkboxes:
- Alkalmas vagyok a kiválasztott munkakörre
- Képes vagyok angolul kommunikálni az ügyfelekkel, ha szükséges
- Szívesen dolgozom agilis módszertannal
- Minden információt elolvastam a cégről

**Comment by herflis** [comment]
The success message should be also translated:

"Sikeresen jelentkeztél!
Köszönettel vettük jelentkezésed a Sense/Net csapatába. 
Rövidesen kapsz tőlünk egy visszaigazoló levelet, majd 1-2 napon belül keresni fogunk megadott elérhetőségeid egyikén!
Hamarosan találkozunk :)
Üdv,
A Sense/Net Csapata"

**Comment by borsi** [comment]
How about

> Successful application!
> 
> We are really happy that one of our job listings caught your interest!
> You'll soon recieve a confirmation e-mail and we'll get back to you in 1 or 2 days using one of your contacts.
> 
> Looking forward to meeting you soon!
> 
> Best,
> Sense/Net Inc. Team

?

**Comment by herflis** [comment]
Maybe the the confirmation email part could be removed because there's no confirmation email anymore :)

**Comment by borsi** [comment]
Yes 👍
