### ISSUE TITLE
SEO issues on sensenet.com

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-resources#24]
# Issue list:
- [x] Several pages have multiple H1 tags. Each page should only have one
- [x] Use case links should appear in the footer so these pages can be 'hoisted' up the sitemap hierarchy

_note: we have additional docs, please ask for them when you start working on the issue_

**Comment by herflis** [comment]
Pls check the footer with the new usecases link list [here](https://sncom.test.sensenet.com/)

**Comment by balazskeszei** [comment]
ok for me
