### ISSUE TITLE
Site CR&Bug pack - Sprint 136

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-resources#29]
# CR's
- [x] On the main page, link "Sensenet ECM" to the product page. There are a lot of clicks on it. See where they want to go.
- [x] Delete the address and map
# Bugs
- [x] Jobs site job urls are Root-type urls: https://jobs.sensenet.com/Root/Sites/Jobs/Teams/codefirst/fullstack. Change them to 'normal' ones.
- [x] When changing a page url in jekyll, it registers in google as a 404 page. This generates a lot of 404 pages, which should be automatic redirects. Check if there's a plugin to achieve this desired behaviour.

**Comment by herflis** [comment]
@borsi Is there a list with the pages registered with 404?

**Comment by borsi** [comment]
@herflis These urls have been removed from google registry in the mean time. However we should be aware of the dummy links we put in documents that not yet point to anywhere. (those can quickly become 404 errors in the future)
