### ISSUE TITLE
sncom misc tasks

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-resources#46]
We have some final tasks before handing the project over to support. And then we hand it over to support.

Tasks:
- [x] Some fields don't work in the contact us form, or the reminder e-mail. These are: Company Name, Company Website, Comment - Comment should be mandatory
- [x] Add an additional mandatory checkbox for the sandbox subscribe forms with the text "I have read and accept the Privacy Policy." - The Privacy Policy should link to our Privacy Policy
- [x] When sumbitting to either contact us, or sandbox, we should submit the e-mail address in Jumplead via the Jumplead API
- [x] Change the old icon url at the bottom of the page to the visualcms url
- [x] Transfer the jobs.sensenet.com and the sensenet.com projects over support.
- [x] Add the same form header to the jumplead form as we have on the contact us page

**Comment by balazskeszei** [comment]
Please add "Read our privacy policy" text and link to the main site as well. Next to"© Copyright Sense/Net Inc · Powered by sensenet ECM Enterprise" text.

**Comment by herflis** [comment]
@balazskeszei I cannot put it under the copyright part, it doesn't fit the design

**Comment by balazskeszei** [comment]
@herflis what about under/next to "Company" on the right side? Just write "Privacy Policy" with the link.
