### ISSUE TITLE
[sncom] Make sensenet.com great again

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-resources#47]
**A/B test schedule**

- [ ] **Contact us lite (Contact us variant test take 2)**
Duration: 20 days
Total sessions: 81
Performance: 89%

- [ ] **Contact us button highlight (sn color)**

**Comment by huszerlbence** [comment]
**A/B testing framework**

Session duration: 2 weeks (14 days)
No parallel tests
1 variant/session (+baseline)
Metric: Probability to beat baseline

Evaluation criteria: "probability to beat baseline" should be at least 70%
In case of positive evaluation: execute changes after approval
In case of negative evaluation: no changes (further tests with other changes are possible)

Log results to test sessions

Schedule: based on suggestions in this epic
