### ISSUE TITLE
Processing the results of sensenet.com metrics

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-resources#70]
- [x] Check random videos in hotjar
- [x] Check the survey submissions
- [x] Create a list with the things that could be remove/are unnecessary/should be revisited
- [x] Create a list with the most clicked things
- [x] Create a list with things that should be highlighted more

**Comment by CsabaPeter** [comment]
**Unnecessary/needs to be revisited:** 
- Survey popup --> a lot of people just pressed the X button right away. It is more of a disruption.
- Jobs should be moved to the footer
- No need for 2 contact us buttons on the same page
![sn](https://user-images.githubusercontent.com/38352683/61206829-d1490c80-a6f3-11e9-9529-5984a7e78f2f.png)
- Remove read more about licencing button instead make a page with clear and short feature list
  https://www.contentful.com/pricing/

**Most clicked**
- Services
- Pricing
- Sn logo
- Documentation

**Should be more highlighted**
- Contact and Try for free could be a floating header so it will be always highlighted
![content](https://user-images.githubusercontent.com/38352683/61207024-57fde980-a6f4-11e9-996d-79d4b1fbc8bb.png)
